const data = [
    {
      question: "What is React?",
      option1: "A UI library",
      option2: "A database",
      option3: "A programming language",
      option4: "A framework",
      ans: 1,
    },
    {
      question: "Who developed React?",
      option1: "Microsoft",
      option2: "Google",
      option3: "Facebook",
      option4: "Amazon",
      ans: 3,
    },
    {
      question: "What is the virtual DOM in React?",
      option1: "A copy of the real DOM",
      option2: "A database",
      option3: "A part of React Router",
      option4: "An HTML element",
      ans: 1,
    },
    {
      question: "What is the purpose of 'useState' in React?",
      option1: "To manage component lifecycle",
      option2: "To manage state in functional components",
      option3: "To render components",
      option4: "To create class components",
      ans: 2,
    },
    {
      question: "Which of the following is a lifecycle method in React?",
      option1: "componentDidMount",
      option2: "renderMethod",
      option3: "initState",
      option4: "startComponent",
      ans: 1,
    },
    {
      question: "What does JSX stand for?",
      option1: "JavaScript XML",
      option2: "JavaScript Extension",
      option3: "Java Syntax Extension",
      option4: "JSON XML",
      ans: 1,
    },
    {
      question: "What is the default state of a React component?",
      option1: "undefined",
      option2: "null",
      option3: "false",
      option4: "state variable",
      ans: 1,
    },
    {
      question: "Which hook is used to manage side effects in React?",
      option1: "useState",
      option2: "useEffect",
      option3: "useReducer",
      option4: "useCallback",
      ans: 2,
    },
    {
      question: "What is a higher-order component?",
      option1: "A function that takes a component and returns a new component",
      option2: "A component that renders itself",
      option3: "A component with multiple states",
      option4: "A React lifecycle method",
      ans: 1,
    },
    {
      question: "Which of the following is true about React keys?",
      option1: "They help React identify which items have changed",
      option2: "They are used to style components",
      option3: "They are mandatory for functional components",
      option4: "They are used to fetch data",
      ans: 1,
    },
  ];
  
  export default data;
  