const data = [
    {
      question: "What does CSS stand for?",
      option1: "Creative Style Sheets",
      option2: "Cascading Style Sheets",
      option3: "Colorful Style Sheets",
      option4: "Computer Style Sheets",
      ans: 2,
    },
    {
      question: "Which property is used to change the background color?",
      option1: "bgcolor",
      option2: "background-color",
      option3: "color",
      option4: "background",
      ans: 2,
    },
    {
      question: "How do you add a comment in CSS?",
      option1: "// This is a comment",
      option2: "<!-- This is a comment -->",
      option3: "/* This is a comment */",
      option4: "# This is a comment",
      ans: 3,
    },
    {
      question: "Which CSS property controls the text size?",
      option1: "text-size",
      option2: "font-size",
      option3: "font-style",
      option4: "text-style",
      ans: 2,
    },
    {
      question: "What is the correct CSS syntax to change the font name?",
      option1: "font-family: Arial, sans-serif;",
      option2: "font: Arial, sans-serif;",
      option3: "font-name: Arial, sans-serif;",
      option4: "text-font: Arial, sans-serif;",
      ans: 1,
    },
    {
      question: "Which property is used to change the font of an element?",
      option1: "font-weight",
      option2: "font-style",
      option3: "font-family",
      option4: "font-size",
      ans: 3,
    },
    {
      question: "What is the default value of the position property?",
      option1: "static",
      option2: "relative",
      option3: "absolute",
      option4: "fixed",
      ans: 1,
    },
    {
      question: "How can you make a list that lists its items with squares?",
      option1: "list-type: square;",
      option2: "list-style-type: square;",
      option3: "list-type: square;",
      option4: "list-style: square;",
      ans: 2,
    },
    {
      question: "Which CSS property is used to control the spacing between words?",
      option1: "letter-spacing",
      option2: "word-spacing",
      option3: "spacing",
      option4: "text-spacing",
      ans: 2,
    },
    {
      question: "What is the correct CSS syntax for making all paragraphs bold?",
      option1: "p {font-weight: bold;}",
      option2: "p {text-weight: bold;}",
      option3: "p {font: bold;}",
      option4: "p {weight: bold;}",
      ans: 1,
    },
  ];
  
  export default data;
  